export const metadata = {
  title: "Algemene voorwaarden | Bryan de Zwart Bookings",
  description: "De algemene voorwaarden van Bryan de Zwart Bookings voor boekingen van dj's, artiesten en bands.",
};

const artikelen: { kop: string; tekst: string }[] = [
  { kop: "1. Wie ik ben", tekst: "Deze voorwaarden zijn van toepassing op alle offertes, aanbiedingen en overeenkomsten van BDZ Ventures, handelend onder de naam Bryan de Zwart Bookings, gevestigd aan De Nieuwe Erven 3, unit 13617, 5431 NV Cuijk. KvK 98283731, btw-nummer NL005322714B67. In deze voorwaarden noem ik mijzelf \u201Cik\u201D of \u201CBryan de Zwart Bookings\u201D, en de partij die boekt \u201Cu\u201D of \u201Cde opdrachtgever\u201D. Met \u201Cartiest\u201D bedoel ik iedere dj, zanger, band, act of andere uitvoerende die via mij wordt geboekt." },
  { kop: "2. Toepasselijkheid", tekst: "Deze voorwaarden gelden voor alles wat ik aanbied en lever. Afwijkingen gelden alleen als ik ze schriftelijk heb bevestigd. Wijkt de boekingsbevestiging af van deze voorwaarden, dan gaat de boekingsbevestiging voor. Eigen inkoopvoorwaarden van de opdrachtgever wijs ik uitdrukkelijk van de hand, tenzij ik die schriftelijk heb aanvaard. Is een bepaling uit deze voorwaarden ongeldig, dan blijven de overige bepalingen gewoon gelden." },
  { kop: "3. Mijn rol bij een boeking", tekst: "Ik boek artiesten die ik zelf vertegenwoordig, en artiesten die ik voor u inkoop bij een andere partij. In beide gevallen sluit u de overeenkomst met mij en factureer ik u: ik ben dus uw aanspreekpunt en verantwoordelijk voor de nakoming, ook wanneer ik de uitvoering uitbesteed. Alleen wanneer ik u vooraf schriftelijk laat weten dat ik uitsluitend bemiddel, komt de overeenkomst rechtstreeks tussen u en de artiest of het bureau tot stand en beperkt mijn rol zich tot het tot stand brengen van dat contact." },
  { kop: "4. Aanvraag, offerte en boeking", tekst: "Een aanvraag via de website is vrijblijvend en verplicht u tot niets. Een offerte is geldig gedurende veertien dagen, tenzij er een andere termijn in staat. Een boeking komt tot stand zodra u mijn boekingsbevestiging schriftelijk of per e-mail akkoord geeft, of zodra ik met uw instemming met de uitvoering begin. Vanaf dat moment is de boeking bindend. Optieafspraken zijn pas geldig als ik ze schriftelijk heb bevestigd, met vermelding van de einddatum." },
  { kop: "5. Prijzen", tekst: "De prijzen op deze website zijn richtprijzen inclusief btw, bedoeld om u een indicatie te geven. De prijs die geldt is de prijs in de offerte of boekingsbevestiging. Aan particuliere opdrachtgevers noem ik prijzen inclusief btw; aan zakelijke opdrachtgevers exclusief btw, wat dan ook zo vermeld staat. Reis- en verblijfkosten en eventuele toeslagen worden apart genoemd. Afdrachten aan rechtenorganisaties zoals Buma/Stemra en Sena vallen buiten de prijs; zie artikel 8." },
  { kop: "6. Betaling", tekst: "Facturen betaalt u binnen veertien dagen na factuurdatum en in elk geval v\u00F3\u00F3r het optreden, tenzij we schriftelijk iets anders afspreken. Bij boekingen die ver vooruit worden gemaakt kan ik een aanbetaling vragen. Betaalt u niet op tijd, dan bent u zonder aanmaning in verzuim en mag ik de wettelijke rente in rekening brengen. Bent u particulier, dan bereken ik incassokosten volgens de wettelijke staffel; bent u een bedrijf, dan komen alle redelijke incassokosten voor uw rekening. Klachten over de hoogte van een factuur meldt u binnen veertien dagen." },
  { kop: "7. Uw verplichtingen op de dag zelf", tekst: "U zorgt voor een geschikte en veilige speelplek, voldoende en deugdelijke stroomvoorziening, een deugdelijke ondergrond en overdekking bij buitenoptredens, en voor de faciliteiten die in de boekingsbevestiging of de rider staan. U zorgt ook voor parkeergelegenheid, een bereikbare laad- en losplek en, waar afgesproken, voor eten en drinken. U levert uiterlijk twee weken voor het optreden de praktische gegevens aan: adres, tijden, contactpersoon ter plaatse en telefoonnummer. Levert u dit niet of niet op tijd, dan kan ik niet instaan voor een vlekkeloos verloop." },
  { kop: "8. Vergunningen, geluid en muziekrechten", tekst: "U bent verantwoordelijk voor alle vergunningen en ontheffingen die voor het evenement nodig zijn, en voor het naleven van de daarin gestelde voorwaarden. Gelden er geluidsnormen of is er een geluidsbegrenzer, meld dat dan bij de aanvraag: de artiest moet daar zijn optreden op kunnen afstemmen. De afdracht aan Buma/Stemra en Sena regelt u als organisator, tenzij we schriftelijk iets anders afspreken." },
  { kop: "9. Het optreden zelf", tekst: "De inhoud en samenstelling van het optreden bepaalt de artiest. Een verzoeknummer of een specifieke setlist is bespreekbaar, maar geen recht. Bij een besloten evenement mag u geen kaarten verkopen of het optreden openbaar aankondigen zonder mijn schriftelijke toestemming. Wijzigingen in de samenstelling van een band of act geven u geen recht de boeking te annuleren, zolang de act als geheel gelijkwaardig blijft." },
  { kop: "10. Annulering door u", tekst: "Wilt u een bevestigde boeking annuleren, dan meldt u dat schriftelijk. U bent dan een percentage van het overeengekomen bedrag verschuldigd. Bepalend is het aantal hele dagen tussen de dag waarop ik uw annulering ontvang en de dag van het optreden: meer dan 30 dagen 25%, 15 tot en met 30 dagen 50%, 8 tot en met 14 dagen 75%, en 7 dagen of minder 100%. Wilt u verplaatsen naar een andere datum, dan zoek ik daar graag naar een oplossing zonder annuleringskosten, mits de artiest op de nieuwe datum beschikbaar is. Bent u particulier, dan breng ik nooit meer in rekening dan mijn werkelijke schade: de al gemaakte kosten en de misgelopen inkomsten." },
  { kop: "11. Bedenktijd bij online boeken (particulieren)", tekst: "Boekt u als particulier volledig op afstand, dus via de website, telefoon of e-mail, dan geldt in beginsel een bedenktijd van veertien dagen. Let op: de wet maakt hierop een uitzondering voor diensten op het gebied van vrijetijdsbesteding die op een bepaalde datum worden verricht. Een optreden op een afgesproken datum valt daaronder. Dat betekent dat u bij een boeking voor een concrete datum g\u00E9\u00E9n bedenktijd heeft en de annuleringsregeling van artikel 10 geldt. Ik wijs u daar bij de bevestiging uitdrukkelijk op." },
  { kop: "12. Als het optreden niet door kan gaan", tekst: "Kan een artiest door ziekte, ongeval, extreme weersomstandigheden, overheidsmaatregelen of andere omstandigheden buiten mijn invloed niet optreden, dan meld ik dat zo snel mogelijk. Ik span mij in om gelijkwaardige vervanging te regelen. Gaat u daarmee akkoord, dan blijft de boeking staan. Wilt u geen vervanger, dan wordt de boeking ontbonden en betaal ik het reeds betaalde bedrag terug, verminderd met kosten die ik al aantoonbaar heb gemaakt. Verdere schadevergoeding is in die situatie niet aan de orde." },
  { kop: "13. Aansprakelijkheid", tekst: "Ik ben aansprakelijk voor schade die het gevolg is van een tekortkoming die aan mij is toe te rekenen. Die aansprakelijkheid is beperkt tot het factuurbedrag van de betreffende boeking, of, als mijn verzekering uitkeert, tot het uitgekeerde bedrag. Ik ben niet aansprakelijk voor indirecte schade zoals gederfde winst of gemiste omzet, en niet voor schade door omstandigheden op de locatie waar ik geen zeggenschap over heb. Deze beperkingen gelden niet bij opzet of bewuste roekeloosheid van mijn kant, en evenmin voor zover de wet ze bij particuliere opdrachtgevers niet toelaat. U bent aansprakelijk voor schade die bezoekers of uw eigen medewerkers toebrengen aan de artiest, aan mijn spullen of aan apparatuur." },
  { kop: "14. Verzekering", tekst: "U zorgt voor een deugdelijke aansprakelijkheidsverzekering voor het evenement. Voor grotere evenementen adviseer ik daarnaast een evenementenverzekering, die dekking kan bieden wanneer het evenement onverhoopt geen doorgang vindt. Het afsluiten daarvan is uw eigen keuze en verantwoordelijkheid." },
  { kop: "15. Beeld en promotie", tekst: "U mag naam en beeldmateriaal van de artiest gebruiken om het evenement aan te kondigen. Ander gebruik, bijvoorbeeld het koppelen van de artiest aan een merk of sponsor, kan alleen met mijn schriftelijke toestemming. Zelf maak ik graag foto's en video's van optredens voor mijn website en sociale media. Dat doe ik alleen met toestemming van de betrokken artiest, dj, band of act. Wilt u niet dat er op uw evenement opnamen worden gemaakt, laat het dan vooraf weten, dan houd ik daar rekening mee." },
  { kop: "16. Klachten", tekst: "Bent u niet tevreden, laat het mij dan weten, het liefst meteen op de dag zelf zodat ik er nog iets aan kan doen, en in elk geval binnen veertien dagen. Ik reageer binnen veertien dagen inhoudelijk. Komen we er samen niet uit, dan staat de gang naar de rechter open." },
  { kop: "17. Toepasselijk recht", tekst: "Op alle overeenkomsten is Nederlands recht van toepassing. Geschillen worden voorgelegd aan de bevoegde rechter in het arrondissement Oost-Brabant. Bent u particulier, dan mag u het geschil ook voorleggen aan de rechter van uw eigen woonplaats." },
];

export default function VoorwaardenPage() {
  return (
    <main className="min-h-screen px-6 pb-24 pt-36">
      <div className="mx-auto max-w-3xl">
        <p className="text-sm font-bold uppercase tracking-[0.2em] text-oranje">Juridisch</p>
        <h1 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">Algemene voorwaarden</h1>
        <p className="mt-6 leading-relaxed text-dim">Bij Bryan de Zwart Bookings staan kwaliteit, duidelijkheid en een zorgeloze samenwerking centraal. Onderstaande voorwaarden zijn van toepassing op alle boekingen en samenwerkingen.</p>

        <div className="mt-12 space-y-8">
          {artikelen.map((a) => (
            <section key={a.kop}>
              <h2 className="mb-3 text-xl font-bold">{a.kop}</h2>
              <p className="leading-relaxed text-dim">{a.tekst}</p>
            </section>
          ))}
        </div>

        <div className="mt-12 rounded-2xl border border-rand bg-kaart p-6">
          <p className="leading-relaxed text-dim">Vragen over deze voorwaarden? Neem contact op via <a href="mailto:info@bdzbookings.nl" className="text-oranje transition hover:opacity-80">info@bdzbookings.nl</a> of bel <a href="tel:+31850606460" className="text-oranje transition hover:opacity-80">085 060 6460</a>.</p>
          <p className="mt-4 text-sm text-dim/70">BDZ Ventures h.o.d.n. Bryan de Zwart Bookings &middot; De Nieuwe Erven 3 unit 13617, 5431 NV Cuijk &middot; KvK 98283731 &middot; btw NL005322714B67 &middot; Laatst bijgewerkt: 6 september 2026</p>
        </div>
      </div>
    </main>
  );
}
